stages:
  - test

sudo: false

language: node_js
node_js:
  - "9.1"

cache:
  directories:
    - node_modules

jobs:
  fast_finish: true 
  include:
    - stage: tests
      name: "test-contracts"
      script: npm run contract:test:coverage
    - stage: tests
      name: "test-contract-lint"
      script: npm run lint:sol
    - stage: tests
      name: "test-dapp-lint"
      script: npm run lint:sol
