version: '3.2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NODE_ENV: development
    volumes:
      - .:/usr/src/app
    ports:
      - 80:3000

  ganache:
    image: trufflesuite/ganache-cli:latest
    # command: --gasLimit 0xfffffffffff -m "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat" -e 100
    command: --gasLimit 0xfffffffffff ${ACCOUNTS}
    ports:
      - 7545:8545 